name: CI
on: [push, release]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        run: curl -L https://foundry.paradigm.xyz | bash
      - name: Run Tests
        run: forge test --match-path test/EntryPointRealTest.t.sol
